services:
  db:
    image: mysql:latest
    restart: always
    container_name: flask-auth-mysql
    environment:
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin123'
      MYSQL_DATABASE: 'flask-crud'
      MYSQL_ROOT_PASSWORD: 'admin123'
    ports:
      - "3306:3306"
    volumes:
      - flask_auth_mysql_data:/var/lib/mysql

volumes:
  flask_auth_mysql_data: